[2018-05-02 20:56:49 +0800] [20249] [INFO] Starting gunicorn 19.8.1
[2018-05-02 20:56:49 +0800] [20249] [INFO] Listening at: http://0.0.0.0:7004 (20249)
[2018-05-02 20:56:49 +0800] [20249] [INFO] Using worker: sync
[2018-05-02 20:56:49 +0800] [20252] [INFO] Booting worker with pid: 20252
[2018-05-02 20:57:04 +0800] [20255] [INFO] Starting gunicorn 19.8.1
[2018-05-02 20:57:04 +0800] [20255] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:04 +0800] [20255] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:05 +0800] [20255] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:05 +0800] [20255] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:06 +0800] [20255] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:06 +0800] [20255] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:07 +0800] [20255] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:07 +0800] [20255] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:08 +0800] [20255] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:08 +0800] [20255] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:09 +0800] [20255] [ERROR] Can't connect to ('0.0.0.0', 7004)
[2018-05-02 20:57:34 +0800] [20260] [INFO] Starting gunicorn 19.8.1
[2018-05-02 20:57:34 +0800] [20260] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:34 +0800] [20260] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:35 +0800] [20260] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:35 +0800] [20260] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:36 +0800] [20260] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:36 +0800] [20260] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:37 +0800] [20260] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:37 +0800] [20260] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:38 +0800] [20260] [ERROR] Connection in use: ('0.0.0.0', 7004)
[2018-05-02 20:57:38 +0800] [20260] [ERROR] Retrying in 1 second.
[2018-05-02 20:57:39 +0800] [20260] [ERROR] Can't connect to ('0.0.0.0', 7004)
[2018-05-02 21:18:20,412] ERROR in app: Exception on /check [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 12, in check
    file.save("queries/a.jpg")
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/datastructures.py", line 2725, in save
    dst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'queries/a.jpg'
[2018-05-02 21:19:52 +0800] [20252] [INFO] Worker exiting (pid: 20252)
[2018-05-02 21:19:52 +0800] [20249] [INFO] Handling signal: term
[2018-05-02 21:19:52 +0800] [20249] [INFO] Shutting down: Master
[2018-05-03 10:16:40 +0800] [17005] [INFO] Starting gunicorn 19.8.1
[2018-05-03 10:16:40 +0800] [17005] [INFO] Listening at: http://0.0.0.0:7004 (17005)
[2018-05-03 10:16:40 +0800] [17005] [INFO] Using worker: sync
[2018-05-03 10:16:40 +0800] [17008] [INFO] Booting worker with pid: 17008
[2018-05-03 10:17:49 +0800] [17020] [INFO] Booting worker with pid: 17020
[2018-05-03 10:17:49 +0800] [17005] [INFO] Handling signal: hup
[2018-05-03 10:17:49 +0800] [17005] [INFO] Hang up: Master
[2018-05-03 10:17:49 +0800] [17022] [INFO] Booting worker with pid: 17022
[2018-05-03 10:17:49 +0800] [17020] [INFO] Worker exiting (pid: 17020)
[2018-05-03 10:38:55 +0800] [18510] [INFO] Starting gunicorn 19.8.1
[2018-05-03 10:38:55 +0800] [18510] [INFO] Listening at: http://0.0.0.0:7004 (18510)
[2018-05-03 10:38:55 +0800] [18510] [INFO] Using worker: sync
[2018-05-03 10:38:55 +0800] [18513] [INFO] Booting worker with pid: 18513
[2018-05-03 10:43:54 +0800] [18666] [INFO] Starting gunicorn 19.8.1
[2018-05-03 10:43:54 +0800] [18666] [INFO] Listening at: http://0.0.0.0:7004 (18666)
[2018-05-03 10:43:54 +0800] [18666] [INFO] Using worker: sync
[2018-05-03 10:43:54 +0800] [18669] [INFO] Booting worker with pid: 18669
[2018-05-03 19:13:25 +0800] [23037] [INFO] Booting worker with pid: 23037
[2018-05-03 19:13:25 +0800] [18666] [INFO] Handling signal: hup
[2018-05-03 19:13:25 +0800] [18666] [INFO] Hang up: Master
[2018-05-03 19:13:25 +0800] [23039] [INFO] Booting worker with pid: 23039
[2018-05-03 19:13:25 +0800] [23037] [INFO] Worker exiting (pid: 23037)
[2018-05-21 15:29:53 +0800] [12781] [INFO] Starting gunicorn 19.8.1
[2018-05-21 15:29:53 +0800] [12781] [INFO] Listening at: http://0.0.0.0:7004 (12781)
[2018-05-21 15:29:53 +0800] [12781] [INFO] Using worker: sync
[2018-05-21 15:29:53 +0800] [12784] [INFO] Booting worker with pid: 12784
[2018-05-21 16:54:54 +0800] [13478] [INFO] Booting worker with pid: 13478
[2018-05-21 16:54:54 +0800] [12781] [INFO] Handling signal: hup
[2018-05-21 16:54:54 +0800] [12781] [INFO] Hang up: Master
[2018-05-21 16:54:54 +0800] [13479] [INFO] Booting worker with pid: 13479
[2018-05-21 16:54:54 +0800] [13478] [INFO] Worker exiting (pid: 13478)
[2018-05-21 20:31:21 +0800] [15618] [INFO] Starting gunicorn 19.8.1
[2018-05-21 20:31:21 +0800] [15618] [INFO] Listening at: http://0.0.0.0:7004 (15618)
[2018-05-21 20:31:21 +0800] [15618] [INFO] Using worker: sync
[2018-05-21 20:31:21 +0800] [15621] [INFO] Booting worker with pid: 15621
[2018-05-21 20:31:24 +0800] [15618] [INFO] Handling signal: hup
[2018-05-21 20:31:24 +0800] [15618] [INFO] Hang up: Master
[2018-05-21 20:31:24 +0800] [15625] [INFO] Booting worker with pid: 15625
[2018-05-21 20:49:39 +0800] [15618] [INFO] Handling signal: term
[2018-05-21 20:49:39 +0800] [15625] [INFO] Worker exiting (pid: 15625)
[2018-05-21 20:49:39 +0800] [15618] [INFO] Shutting down: Master
[2018-05-21 21:37:22 +0800] [16320] [INFO] Starting gunicorn 19.8.1
[2018-05-21 21:37:22 +0800] [16320] [INFO] Listening at: http://0.0.0.0:7004 (16320)
[2018-05-21 21:37:22 +0800] [16320] [INFO] Using worker: sync
[2018-05-21 21:37:22 +0800] [16323] [INFO] Booting worker with pid: 16323
[2018-05-21 21:38:03 +0800] [16328] [INFO] Booting worker with pid: 16328
[2018-05-21 21:38:03 +0800] [16320] [INFO] Handling signal: hup
[2018-05-21 21:38:03 +0800] [16320] [INFO] Hang up: Master
[2018-05-21 21:38:03 +0800] [16329] [INFO] Booting worker with pid: 16329
[2018-05-21 21:38:04 +0800] [16328] [INFO] Worker exiting (pid: 16328)
[2018-05-22 06:43:23,406] ERROR in app: Exception on /paper/check [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 10, in check
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: 'undefined'
[2018-05-22 06:44:05,211] ERROR in app: Exception on /paper/check [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 10, in check
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: 'undefined'
[2018-05-22 06:45:24,926] ERROR in app: Exception on /paper/check [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 10, in check
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: 'undefined'
[2018-05-22 07:00:26,313] ERROR in app: Exception on /paper/check [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 10, in check
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: 'undefined'
[2018-05-22 09:55:29,419] ERROR in app: Exception on /paper/check [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 10, in check
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: ''
[2018-05-22 14:52:48,709] ERROR in app: Exception on /paper/check_v2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 26, in check_v2
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: ''
[2018-05-22 14:53:10,112] ERROR in app: Exception on /paper/check_v2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 26, in check_v2
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: ''
[2018-05-22 14:53:32,992] ERROR in app: Exception on /paper/check_v2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 26, in check_v2
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: ''
[2018-05-22 14:53:38,857] ERROR in app: Exception on /paper/check_v2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 26, in check_v2
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: ''
[2018-05-22 14:54:11,645] ERROR in app: Exception on /paper/check_v2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 26, in check_v2
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: ''
[2018-05-22 14:56:47,075] ERROR in app: Exception on /paper/check_v2 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/wwwroot/yun.chinadream.org/paper/app.py", line 26, in check_v2
    limit = int(request.form['limit'])
ValueError: invalid literal for int() with base 10: ''
